### ISSUE TITLE
Currently it's not buildable and not working properly with Opencart

### ISSUE THREAD

**Issue by szabcsee** [DockerIt/opencart-docker#11]
I think the mysqli module is not enabled at all and it can not connect to the database.
I need to check again, but I think the file placement (/www, /upload etc.) are also not consistent between the containers.

**Comment by eugen-vg** [comment]
This PR contains the commits needed to build the images https://github.com/DockerIt/opencart-docker/pull/14. Regarding file placements, you need to adjust WEB_DOCUMENT_ROOT in the ../apache/Dockerfile and specify correct paths into volumes of docker-compose.yml. As example:
```
volumes:
  - ../src:/var/www
```

Upd: merged
