### ISSUE TITLE
Got Error: Failed to connect to database. Reason: 'SQLSTATE[HY000] [2002] Connection refused' 

### ISSUE THREAD

**Issue by treenwang** [DockerIt/opencart-docker#5]
I used default configuration in MacBook got error
 Failed to connect to database. Reason: 'SQLSTATE[HY000] [2002] Connection refused' 
When install in step 3.

**Comment by numberformat** [comment]
Based on my experience mysql:latest did not work. Downgrade to a prior version. Checkout my pull request for the fix.

**Comment by matt-t-d** [comment]
mysql version is now explicitly set
