### ISSUE TITLE
docker-compose failed

### ISSUE THREAD

**Issue by chengkinhung** [DockerIt/opencart-docker#7]
$ docker-compose up -d apache mysql
...
Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libpng12-dev' has no installation candidate
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y 	libfreetype6-dev 	libjpeg62-turbo-dev 	libmcrypt-dev 	libpng12-dev     curl' returned a non-zero code: 100

**Comment by matt-t-d** [comment]
One year on... this should now be fixed
